### ISSUE TITLE
Notebooks 2.0 // Controller // Implement Culling

### ISSUE THREAD

**Issue by thesuperzapper** [kubeflow/notebooks#38]
related https://github.com/kubeflow/notebooks/issues/85

Now that https://github.com/kubeflow/notebooks/pull/34 is merged, there are only a small number of remaining tasks for the ["Kubeflow Workspaces Controller](https://github.com/kubeflow/notebooks/tree/notebooks-v2/workspaces/controller) to be finished.

One task is to implement the culling functionality of the WorkspaceKinds, which will automatically pause Workspaces which are not used for a period of time.  Unlike in Notebooks 1.0, we now support arbitrary "activity probes", in addition to a direct integration with JupyterLab.

# Implementation

We will create a separate controller loop that checks for Workspaces needing a probe on some regular interval, and triggers a “reconcile” (which is actually a “probe” in this case, but the function is still called `Reconcile()`) and then either culls the Workspace or updates its status information).

Definition of “workspace needing probe”:
- The workspace has a Running state
- The “last activity” was more than “Max Inactive Seconds” ago OR the “last update” was more than “maximum probe interval” seconds ago. 
- However, NO PROBE should be made if the last "last probe time" was less than "minimum probe interval" seconds ago.

## CRDs

This section of the [`WorkspaceKind` definition](https://github.com/thesuperzapper/kubeflow-notebooks-v2-design/blob/main/crds/workspace-kind.yaml) is where users will define and configure their culling probes:

```yaml
spec:
  podTemplate:

    ## activity culling configs (MUTABLE)
    ##  - for pausing inactive Workspaces
    ##
    culling:

      ## if the culling feature is enabled
      ##
      enabled: true

      ## the maximum number of seconds a Workspace can be inactive
      ##
      maxInactiveSeconds: 86400

      ## the probe used to determine if the Workspace is active
      ##
      activityProbe:

        ## OPTION 1: a shell command probe
        ##  - if the Workspace had activity in the last 60 seconds this command
        ##    should return status 0, otherwise it should return status 1
        ##
        #exec:
        #  command:
        #    - "bash"
        #    - "-c"
        #    - "exit 0"

        ## OPTION 2: a Jupyter-specific probe
        ##  - will poll the `/api/status` endpoint of the Jupyter API, and use the `last_activity` field
        ##    https://github.com/jupyter-server/jupyter_server/blob/v2.13.0/jupyter_server/services/api/handlers.py#L62-L67
        ##  - note, users need to be careful that their other probes don't trigger a "last_activity" update
        ##    e.g. they should only check the health of Jupyter using the `/api/status` endpoint
        ##
        jupyter:
          lastActivity: true

          ## NOTE: this is NEW, otherwise, if multiple ports are defined, we dont know which to probe
          portId: "jupyterlab"
```

### Changes from current CRDs

After designing and discussing this implementation, we figured that we need to make some small additions to the existing Notebooks 2.0 CRDs:

- Workspace:
     - Add `spec.disableCulling` which defaults to `false`, and if `true` we will never cull the Workspace.
     - Status:
          - Add `status.activity.lastProbe` (see https://github.com/kubeflow/notebooks/issues/38#issuecomment-2338852756)
- WorkspaceKind:
     - Add `spec.podTemplate.culling.minProbeInterval` which determines the minimum period between each Workspace probe (this prevents too many probes being made when the probe is failing)
     - Add `spec.podTemplate.culling.maxProbeInterval` which determines the maximum period between each Workspace probe (this ensures we probe at least this frequently, to ensure our UI information is "fresh").
     - Add `spec.podTemplate.culling.activityProbe.jupyter.portId` to select which port to run the probe against.

### Jupyter Probe

The culling controller will do the following on its "reconciliation" loop for the Jupyter-type probe:

1. Make an HTTP request to the `/api/status` endpoint of the Pod:
     - ?? it might be possible to use the Kubernetes `/exec` api to make an HTTP request also, not sure
2. Set the “Last update” to the time we STARTED sending the request.
3. Set the “Last activity” to the `last_activity` field returned by the Jupyter API:
      - https://github.com/jupyter-server/jupyter_server/blob/v2.13.0/jupyter_server/services/api/handlers.py#L62-L67
4. Update the status of the Workspace resource with the new activity values.
5. Apply culling:
     - If the “last activity” is more than “Max Inactive Seconds” ago (with 5 seconds of buffer), cull the Workspace (unless “disable culling” is true for the Workspace)

### Bash Probe

The culling controller will do the following on its "reconciliation" loop for the Bash-type probe:

1. Send bash commands to the pod via the Kubernetes `/exec` API:
     - If the bash command exists with anything other than 1 or 0, don’t continue and possibly raise a warning in the logs.
     - NOTE: exit 0 -> there has not been activity in the past 60 seconds
     - NOTE: exit 1 -> there has been activity in the past 60 seconds
     - We should time out the bash command after 55 seconds (and assume that there WAS activity):
          - !! we need to document that the bash probe must take less than 55 seconds.
2. Set “Last Update” to the time we STARTED sending the bash command to the pod.
3. Set “Last Activity”:
      - If the bash probe exits with 0, the “last activity” should not be updated (unless it’s currently 0, then it should be the current time)
      - If the bash probe exits with 1, the “last activity” should be set to the current time.
4. Update the status of the Workspace resource with the new activity values.
5. Apply culling:
      - If the “last activity” is more than “Max Inactive Seconds” ago (with 5 seconds of buffer), cull the Workspace (unless “disable culling” is true for the Workspace)

# Future Work

- Consider having a TTL (time to live) concept for Workspaces, where the workspace has a set "expiry time" (probably stored in the Workspace spec):
    - Users would have to explicitly extend the life of the Workspace, otherwise it would be automatically paused at the expiry time. Users would probably need to use the UI to "extend the life" of the Workspace.
    - We could even get really fancy and integrate an __email reminder system__, similar to what Google Collab and other paid notebook services use.

**Comment by dionathanfreitas** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Amrithesh-k** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by thesuperzapper** [comment]
@jiridanek @Adembc, @kimwnasptd, or @ederign you might be interested in picking this up, it's one of the two remaining tasks to finish the Notebooks 2.0 controller.

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Adembc** [comment]
I will take it @thesuperzapper

**Comment by thesuperzapper** [comment]
@Adembc I realized that we also need to add `spec.podTemplate.culling.activityProbe.jupyter.portId` so we know which port to probe with the Jupyter HTTP requests.

**Comment by thesuperzapper** [comment]
@Adembc as we discussed today, we need to make a few changes to the implementation:

1. Rename `minimumProbeInterval` to `maxProbeInterval`, as it is more correct to say the "maximum time between probes", because this is the maximum INTERVAL:
2. Add a new `minProbeInterval` (on WorkspaceKind) which limits how frequently the probes can be made (to avoid spamming with probes on failure)
3. To enable `minProbeInterval`, we need to add the following new status fields to WorkspaceKind:

```yaml
status:
  activity:
    ...

    ## information about the last activity probe
    lastProbe:
      ## the time the probe was started (UNIX epoch in milliseconds)
      startTimeMs: 1710435303000

      ## the time the probe was completed (UNIX epoch in milliseconds)
      endTimeMs: 1710435305000

      ## the result of the probe
      ##  - ENUM: "Success" | "Failure" | "Timeout"
      result: "Success"

      ## a human-readable message about the probe result
      ##  - WARNING: this field is NOT FOR MACHINE USE, subject to change without notice
      ##  - EXAMPLES:
      ##     - "Jupyter probe succeeded"
      ##     - "Jupyter probe failed: HTTP 500"
      ##     - "Jupyter probe failed: invalid response body"
      ##     - "Jupyter probe failed: timeout after 5000ms"
      ##     - "Bash probe succeeded"
      ##     - "Bash probe failed: unexpected exit code 100"
      ##     - "Bash probe failed: timeout after 5000ms"
      message: ""
```

4. When implementing the bash probe, we probably need to either:
      1. Import the whole `kubectl` package into the controller
      2. OR: if possible, use the existing `kuberntes-go` library, similar to what [this stack overflow](https://stackoverflow.com/a/58297576/5030772) said. However, this might not work because they recently switched to using WebSockets on the Kubernets exec API.
